{
    "config": {
        "error": {
            "cannot_connect": "Ha fallat la connexi\u00f3",
            "invalid_auth": "Autenticaci\u00f3 inv\u00e0lida",
            "unknown": "Error inesperat"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Contrasenya",
                    "username": "Nom d'usuari"
                },
                "description": "El dispositiu IoTawatt necessita autenticaci\u00f3. Introdueix el nom d'usuari i la contrasenya i fes clic al bot\u00f3 Envia."
            },
            "user": {
                "data": {
                    "host": "Amfitri\u00f3"
                }
            }
        }
    }
}